#!/usr/bin/python
import requests
import sys
import re

if __name__ == "__main__":

    url = "https://teaching.doc.ic.ac.uk/wacc_compiler/run.cgi"

    payload = {
                "options[]" : "-a",
                "stdin"   : ""
              }

    testfile = {
                 "testfile" : open(sys.argv[1], 'rb')
               }

    response = requests.post(url, data=payload, files=testfile)
    js = response.json()
    out = js["compiler_out"]
    delim = "==========================================================="
    try:
        start = out.index(delim) + len(delim)
        end = out.index(delim, start)
        ass = out[start:end]
    except ValueError:
        ass = "Did not assemble"
    remove_line_no = re.sub(r"\d+\t", r"\t", ass)
    print remove_line_no
